### ISSUE TITLE
Error when converting any objects

### ISSUE THREAD

**Issue by Flandyn** [Markemp/Cryengine-Converter#10]
Whenever I try to convert something, the program gives me this error:

********************************************************************************
There was an error rendering 
*"file to convert"*

Object reference not set to an instance of an object.

   at CgfConverter.Program.Main(String[] args)
********************************************************************************

**Comment by Markemp** [comment]
Which game are you trying to convert?  And can you post a screenshot of when you run the command too?

**Comment by Flandyn** [comment]
Game: Star Citizen
Tested with cgf-converter v1.0.2, v1.0.1 v1.0.0 and building from source. Only v1.0.0 works without this issue, but has broken UVs, which is why I am not using it.
Screenshot: 
![cmd2](https://user-images.githubusercontent.com/15834268/35498309-2379a308-04ce-11e8-86f5-9a5ccc94ed38.png)
I also tried `foreach ($file in (get-childitem -recurse *.cga,*.cgf,*.chr,*.skin)) { .\cgf-converter $file -objectdir Objects }` in PowerShell as stated in the README file. This is what happens:
![powershell](https://user-images.githubusercontent.com/15834268/35498615-5437d81a-04cf-11e8-8350-01f5c925f6e5.PNG)
It might seem as if it is converting, but if I try and find the converted files, there aren't any.

**Comment by Markemp** [comment]
It looks like the -objectdir variable should be "d:\starcitizen", not "Objects".  Can you rerun the powershell command and Gladius again with the proper objectdir?

There should be a bunch of .dae files in the directories as well.  I'll take a look at my version and see if there is something wrong with that set in particular.

**Comment by Flandyn** [comment]
Fixed. However, when importing the .dae the normals seem to be broken. Here are some screenshots:
![normals01](https://user-images.githubusercontent.com/15834268/35511635-f37853be-04fc-11e8-973a-3331db756926.PNG)
![normals02](https://user-images.githubusercontent.com/15834268/35511636-f5afc87e-04fc-11e8-9dec-771f775ce716.PNG)
When using `-obj` this problem does not occur, however the UVs are still broken but in .dae they are not.
Also, when trying to import .obj files the program crashes, meaning I have to import the .obj files into another program and export them as .fbx . This is not an issue with the program as importing other .obj files does not cause a crash.
