### ISSUE TITLE
Broken UVs for .obj, broken normals for .dae.

### ISSUE THREAD

**Issue by Flandyn** [Markemp/Cryengine-Converter#11]
When importing the converted .dae files the normals seem to be broken:
![normals01](https://user-images.githubusercontent.com/15834268/35511635-f37853be-04fc-11e8-973a-3331db756926.PNG)
![normals02](https://user-images.githubusercontent.com/15834268/35511636-f5afc87e-04fc-11e8-9dec-771f775ce716.PNG)
When using `-obj` this problem does not occur, however the UVs are broken.
Also, when trying to import .obj files the program crashes, meaning I have to import the .obj files into another program and export them as .fbx . This is not an issue with the program as importing other .obj files works fine. Any ideas as to what might be causing this?

**Comment by Markemp** [comment]
The broken normals are a known issue for Star Citizen files.  They work fine in Blender (which recalculates them), but in programs like Maya it doesn't get them right.  There is another issue opened about this (#5).

I haven't noticed any issues with the UVs though, even for SC.  Can you show some examples?

**Comment by Flandyn** [comment]
Nevermind, the UV issue was caused by Noesis, which I was using to convert the .obj files.
I used Blender instead and it works.

It would be easier to just import the .obj files though, instead of having to process them though Blender.
Do you know why importing the .obj files into certain programs crashes them?
