### ISSUE TITLE
Star Citizen Texture Paths are Wrong

### ISSUE THREAD

**Issue by SMLudwig** [Markemp/Cryengine-Converter#113]
When I import a Star Citizen 3.14.1 ship into Blender 2.93 (e.g. AEGS Avenger), I get the model without textures. Running Blender in the Windows Power Shell shows that the texture files are not found when importing the model (many <code>Image not found</code> warnings).

An example is this path: <code>Data\Objects\objects\spaceships\ships\aegs\textures\exterior\metal\textures\aegs_avenger_pads_ddna.dds</code>
I checked and found the file here:
<code>Data\Objects\objects\spaceships\ships\aegs\textures\exterior\metal\aegs_avenger_pads_ddna.dds</code>
Somehow the \textures\ folder was added to all the image paths.

Second example:
<code>Data\Objects\textures\defaults\textures\white.dds</code>
I found the file in this path:
<code>Data\Objects\textures\defaults\white.dds</code>

I also opened a .dae file in the text editor and saw that indeed the \textures\ folder was wrongly in all the paths.

I converted the full Star Citizen build with this command:
<code>foreach ($file in (get-childitem -recurse *.cga,*.cgf,*.chr,*.skin)) { C:\Users\Shadow\Documents\StarCitizenBlender\cgf-converter.exe $file -noconflict -objectdir "C:\Users\Shadow\Documents\Star Citizen Blender\blender_advocacy_tracker\Data\" }</code>

I then also tried re-converting the Avenger specifically with this command, specifying the actual Objects path:
<code>foreach ($file in (get-childitem -recurse *.cga,*.cgf,*.chr,*.skin)) { .\cgf-converter.exe $file -noconflict -objectdir "C:\Users\Shadow\Documents\Star Citizen Blender\blender_advocacy_tracker\Data\Objects\" }</code>

Any idea what is going on?
Thanks

**Comment by Kjasi** [comment]
First of all, make sure you convert the DDS files. SC likes to break them up based on their mip-map size. There's programs for fixing that, but Blender can't read the extracted files, so they might show up as `Image not found`.

As for the extra `textures` in the image paths, that's odd. We'll have to look into it.

**Comment by SMLudwig** [comment]
Thanks for looking into it. Looks like all of the textures are affected as far as I can tell. Here are some screenshots:

![2021-09-30_blender_1](https://user-images.githubusercontent.com/43244017/135400611-7b5a5a2d-8df2-458d-bed2-6e9dbf5a63c3.PNG)

![2021-09-30_blender_2](https://user-images.githubusercontent.com/43244017/135400718-baf6ba27-084d-4d06-b12f-ae32427661a9.PNG)

![2021-09-30_blender_3](https://user-images.githubusercontent.com/43244017/135400735-f3ea990f-ae63-4287-b058-e0b32762726c.PNG)

**Comment by Markemp** [comment]
This should have been fixed as of 1.4.0.  Can you confirm that it's still an issue?

The old logic tried to find the materials based on some assumptions.  But 1.4 added a lot better material handling, and it should be able to find them from the `-objectdir` parameter if you pass it in.

Oh... just noticed.  Don't include `Objects` in the -objectdir parameter.  Just point to the root.  That may have been the original issue.

**Comment by Markemp** [comment]
Closing as resolved (issue is wrong path used in `-objectDir` argument).
