### ISSUE TITLE
Cryengine-Converter (cgf-exporter)  dont work

### ISSUE THREAD

**Issue by NomadX688** [Markemp/Cryengine-Converter#115]
I tried convert  file format  skin and cgf  from crysis 3 remastered.

**Comment by Markemp** [comment]
Can you provide some more information?  Which models, was there any output from the converter, etc?  Thanks.

**Comment by NomadX688** [comment]
Model nanosuit, weapon.
When i throw file format  skin and cgf  on  cgf-exporter nothing is happening.

**Comment by Markemp** [comment]
Can you take a screen shot of your terminal from when you run the command?

**Comment by NomadX688** [comment]
![Снимок экрана 2021-11-23 161012](https://user-images.githubusercontent.com/94874060/143029937-d2259537-9afd-42a7-b171-ba5438303794.png
![Снимок экрана 2021-11-23 160944](https://user-images.githubusercontent.com/94874060/143029962-0e22190a-c058-47de-9c44-a3a7456efc94.png)
![Снимок экрана 2021-11-23 160902](https://user-images.githubusercontent.com/94874060/143029976-7072f56b-b5f3-4404-8d10-a44d0709ca98.png)
)

**Comment by NomadX688** [comment]
![Снимок экрана 2021-11-23 161012](https://user-images.githubusercontent.com/94874060/143030067-6319b0ef-8125-4529-8f16-9e8db46fee58.png)

**Comment by Markemp** [comment]
It looks like you have a space between `cgf-converter` and `.exe`.  Those should be together, not separated by a space (i.e. `cgf-converter.exe`).  Can you try it like that?

**Comment by NomadX688** [comment]
![Снимок экрана 2021-11-23 171147](https://user-images.githubusercontent.com/94874060/143040079-b2b52b99-7fb7-41ee-9bfe-002ff9d5c58f.png)
![Снимок экрана 2021-11-23 171218](https://user-images.githubusercontent.com/94874060/143040087-8f1fa342-7096-43bf-a97a-cd288838a0fa.png)
![Снимок экрана 2021-11-23 171302](https://user-images.githubusercontent.com/94874060/143040093-53b4f7b1-8ad8-447f-a713-d7996b0132e8.png)

**Comment by Kjasi** [comment]
From the nanosuit directory, try `d:/cgf/cgf-converter.exe ./nanosuit_v2_helmet.skin -dae`

**Comment by NomadX688** [comment]
![Снимок экрана 2021-11-24 004655](https://user-images.githubusercontent.com/94874060/143134386-a887ff62-0f46-4f87-a59d-b0517c6cb6c7.png)
Everything works but i needed to  installation  NET SDK 5.0  thank you very much for your help

**Comment by Markemp** [comment]
You should be able to just install the runtime. And auto update should make sure that it's available as well. Are you not on Windows 10, or maybe have updates turned off?

**Comment by NomadX688** [comment]
Yes,updates turned off
