### ISSUE TITLE
Conflict in chunk definition

### ISSUE THREAD

**Issue by GeorgiaGrace** [Markemp/Cryengine-Converter#116]
**Describe the bug**
When running the cgf-converter command, there are a few failures that arise with the error: "Conflict in chunk definition". This occurs in most of the models, but to keep it simple we'll stick to the MWO Awesome model. When I get this error and try to import the mech to blender via the Mech Importer tool, I get this error in the Blender logs: 

"Python: Traceback (most recent call last):
  File "C:\Users\Cameron\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_cryengine_importer\__init__.py", line 176, in execute
    Cryengine_Importer.import_mech(context, **keywords)
TypeError: import_mech() got an unexpected keyword argument 'relpath'

location: <unknown location>:-1"

Here is the full log of running the cgf-converter command from the Awesome's body folder:

PS F:\Depot\MWO2\mechs\Objects\mechs\awesome\body> cgf-converter *.cga -objectdir "F:\Depot\MWO2\mechs"
Conflict in chunk definition
13D4+44
F254+44
Conflict in chunk definition
1418+C0
F298+C0
Conflict in chunk definition
14D8+48
F358+48

** Sample Model with the issue
- MWO
- F:\Depot\MWO2\mechs\Objects\mechs\awesome\body

**Additional context**
This model previously converted correctly and was able to import, but applying the variant ddn normal texture to it caused a crash in Cycles so I started over just in case that was the issue. The body ddn normal applied without issue.

**Comment by Markemp** [comment]
The `Conflict in chunk definition` messages are informational only, and don't have any impact on the conversion itself.  I really should have those show only on verbose outputs.  I'll add that to my todo list.

I'm not sure what would cause the unexpected keyword argument message though.  This part looks a bit weird to me:
`"C:\Users\Cameron\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_cryengine_importer_init_.py",`
The `io_cryengine-importer` part is a directory, but it looks like it's appending the init part to the dir. 

I just tried it on mine with the Awesome and it was able to import successfully.  Could you remove the old folder and redownload the latest cryengine converter zip folder?

**Comment by JoshVandeleuv** [comment]
I believe that I have a similar, if not identical issue to the one in this report.  Notable differences are that I see far more 'conflict in chunk definition' messages and I receive the same error message when importing (unexpected keyword argument) but without the apparent typo in the path.  My error message shows "\io_cryengine_importer\_init_.py", with the slash in the correct place; perhaps this was a typo on the original reporter's part?

Based on your previous answer, it seems more information may be helpful.  (assuming my issue really is the same.)  The error message doesn't appear every time, but it seems that it's the result of importing multiple times, possibly reset by restarting Blender.  However, when the error message does not appear, only the armature is imported, taking the form of a handful of boxes and spheres.  This is the same result whether I import the .cdf file with the 'import mech' option as detailed in the tutorial videos or whether I open the '.blend' file directly, which leads me to believe that the core issue may be coming from the conversion process (though I admit that I don't have much to base that speculation on)
