### ISSUE TITLE
Would be possible to have an autonomous exe?

### ISSUE THREAD

**Issue by Naimas** [Markemp/Cryengine-Converter#117]
I am not a coder and I tried to follow the tutorials but I always get no results, I tried all ways but I wasn't able to make it work , also perhaps because I have several different Hdds and I don't extract the whole pack file as I don't have space for it I just extract one model and wanted to convert but doesn't work , a more automated process would be more friendly to non programmer users thanks a lot for the hard work anyway .

**Comment by Kjasi** [comment]
First of all, CryEngine models actually reference a lot of different files to make a complete model, so if you don't have them all pulled out, the program won't see them and it can't convert models correctly. (or at all sometimes.)

As for user friendliness, this is more of a command-line tool, which offers greater flexibility, and a faster production time, at the cost of a nice interface.

That said, I know that if you're pulling from Star Citizen, there's a front-end tool that will pull models out without the need to decompress and extract the game files, called SCDV, which you can find here: https://gitlab.com/scmodding/tools/scdv/ I am unaware of similar front-ends for other games.

Probably not the answer you wanted, but this is the current state of the tool. A front-end to make conversion easier would be nice, but a single solution wouldn't work for every game, and such a program would still depend on this program, and you would likely still need to decompress at least some of the files.

**Comment by Markemp** [comment]
Kjasi is correct in his post.  This is more of a tool to assist in a multi step process, and favors flexibility over ease of use for that reason.

However, I have made it extensible (with a flexible license) so that if someone wanted to make a nice front end, they can incorporate it into a front end to make it easier for everyone.

That being said, we're more than happy to help out with specific issues to help with your issues, so just let us know what game you're working with, what you are trying to do, the version of the converter/importer, any error messages it shows, etc.  Thanks!

**Comment by fettness** [comment]
What would be the cost to hire a front end developer? I run a animation company and love sponsoring small projects like this now and then. 
Been trying to get this to work myself and have gotten close but think I am missing a final step. 
I got everything working after downloading  .net 5.0 (6 does not work) but when I get to the final step of converting it just lists how to use the script. 
https://www.dropbox.com/s/xalokopzprf2veo/Screenshot%202021-12-30%20180745.png?dl=0
Think I need to try unpacking everything and matching your original file structure.

**Comment by Markemp** [comment]
Unpacking everything to the original file structure is important, as there are some conventions that Cryengine uses when it's lookin for files.  Usually the converter can just work on the file you are trying to convert though.

The simplest way to run the converter in your case (from the image posted above, and assuming `cgf-converter.exe` is in your path) is just to be in the folder where the asset you want to convert is located and enter:

`cgf-converter.exe <asset name with file extension>`

Give that a try, and if it doesn't work post a reply with the error output, and we can help get to the next step.

**Comment by Markemp** [comment]
Closing this issue.  Let me know if there is anything else I can help with.
