### ISSUE TITLE
[ERROR] "Index was out of range" when attempting to convert a .chr file

### ISSUE THREAD

**Issue by ACluelessFool** [Markemp/Cryengine-Converter#118]
**[Description]**
I was trying to convert two _.chr_ files from [Mechwarrior: Living Legends](https://mechlivinglegends.net/), a Crysis Wars mod, and the script kept throwing up the "Index was out of range" error on both files. Oddly enough, the script worked just fine on the .cga model in the same folder. I'm not sure if the error is occuring because the assets are custom mod assets or if I'm doing something wrong with these files.

I've attached the objects I'm trying to convert, here's the path for them: _...\Living Legends\Objects\objects_mwll\Vehicles\Innersphere\Tracked\IS_Rommel_

---

**[Screenshots]**
![CryEngineConverter_IndexErrors_treadchr](https://user-images.githubusercontent.com/79179692/147494766-41241415-1d1e-4175-b7f0-f555dbbeadd2.png)

---

**[Attachments]**
[IS_Rommel.zip](https://github.com/Markemp/Cryengine-Converter/files/7781174/IS_Rommel.zip)

**Comment by ACluelessFool** [comment]
> I'll take a look at this file soon (in the middle of another project right now). .chr files are generally just armatures, so if you're just looking for the geometry it shouldn't be necessary. But if you're looking to rig the geometry to the armature, it can be handy (as opposed to making your own armature).

I think in the case of Living Legends, its seems that the mod uses the .chr to store geometries for the moving bits - that is to say, the legs of the mechs and the treads of the vehicles; it sounds odd to me but I suppose that's how the game works. Nonetheless, thank you for responding and thank you for the very handy tool!

**Comment by Markemp** [comment]
I think this is fixed.  It was an issue with all 0x744 versions of models due to the converter not supporting the chunk table.  I'll be releasing v1.4.0 here very soon, so let me know if it is still having problems.

**Comment by Markemp** [comment]
Closing issue.
