### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by xkrxdragoon** [Markemp/Cryengine-Converter#12]
I am trying to open up the .cgf file for ppcs inside gamedata/objects/weapons so i can change the color (which im hoping should be simple) of the ppc projectile/beam with a diffuse. 
I cant figure out how to get it open >.<
Would i be able to create a .mtl txt file to put a color shading over the projectile/beam?
Or would i have to find a way to get that .cgf open? if so, how would i go about getting it into a usable program?

(i'm extremely new at this sort of thing, so be gentle ;p)

**Comment by Markemp** [comment]
Can you get a screenshot of the errors you're seeing?  I'm happy to help!

**Comment by xkrxdragoon** [comment]
I'm not quite sure what program i would use to open it so i can change colours and such.
Would your cryengine converter work for this? since its a projectile i wasnt sure since your converter is used mainly for mechs. I had been trying to open it up with Ubisoft cgf model reader and Xnview but that didnt work.
<Effect name="Projectile" asset="objects/weapons/ppc_projectile.cgf" mass="1.0"/>
      <Effect name="ProjectileMaterial" asset="mat_ppc"/>
      <Effect name="Trail" asset="mech_weapons.ppc.beam_trail"/>
      <Effect name="TrailFP" asset="mech_weapons.ppc.beam_trail_fp"/>
Thats the string under weapons.xml for the ppc paths, it would be the .cgf i would need to open yea? or should i be trying to find the "mat_ppc" asset? Not even sure where to look for that since it doesnt have a .file extension. 

Thanks for your quick response!

**Comment by xkrxdragoon** [comment]
<Effect name="Projectile" asset="objects/weapons/ppc_projectile.cgf" mass="1.0"/>
      <Effect name="ProjectileMaterial" asset="mat_ppc"/>
      <Effect name="Trail" asset="mech_weapons.ppc.beam_trail"/>
      <Effect name="TrailFP" asset="mech_weapons.ppc.beam_trail_fp"/>
      <Effect name="Muzzle" asset="mech_weapons.ppc.muzzle_flash"/>
      <Effect name="MuzzleFP" asset="mech_weapons.ppc.muzzle_flash_fp"/>

**Comment by Markemp** [comment]
I'm going back over old issues, and realized I never finished up on this one.  Where are you trying to change the colors?  In the game itself?

**Comment by Markemp** [comment]
This would involve re-paking the files, which isn't something this program supports.  I'm not exactly sure how this could be solved, although there have been some people who modified the sound files in the game.  They may have more info on how to do this.
