### ISSUE TITLE
[Conflict in Chunk Definition] MWO

### ISSUE THREAD

**Issue by Dakkapocalypse** [Markemp/Cryengine-Converter#123]
I'm trying to mass-convert all files for MWO, but I'm getting this error

Additionally, when trying to use the old cryengine importer in Blender 2.79, or the new one in Blender 2.93, I am unable to import any of the files except in their individual formats (.dae, etc) -- the script to reconstruct the mech (.cdf) isn't working.

PS F:\depot> foreach ($file in (Get-ChildItem -Recurse *.cga, *.cgf, *.chr)) { F:\depot\mwo\cgf-converter.exe $file -objectdir "F:depot\mwo"}
Conflict in chunk definition
13C0+D4
5340+D4
Conflict in chunk definition
1494+E8
5414+E8
Conflict in chunk definition
157C+E8
54FC+E8
Conflict in chunk definition
13C0+D4
5340+D4
Conflict in chunk definition

**Comment by Markemp** [comment]
The conflicts in chunk definition messages are just warnings and can be safely ignored.\

Which mech are you trying to import?

**Comment by Dakkapocalypse** [comment]
All of them – but that’s what I’m saying. They all give that problem, and none of them get converted.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by Markemp** [comment]
Can you get a copy of the System Log from when you run the importer in Blender?  You can open that in Blender from `Window -> Toggle System Console` (although it might be Show system console in 2.93?).  Run the importer and copy the output to a file and upload it to this issue.

**Comment by Dakkapocalypse** [comment]
Import Mech
F:\depot\mwo\objects\mechs\bloodasp\bloodasp.cdf
+-- Collada Import parameters------
| input file      : F:\depot\mwo\objects\mechs\bloodasp\body\bloodasp.dae
| use units       : no
| autoconnect     : yes
+-- Armature Import parameters ----
| find bone chains: yes
| min chain len   : 0
| fix orientation : no
| keep bind info  : no
I/O warning : failed to load external entity "file:///F:/depot/mwo/objects/mechs/bloodasp/body/bloodasp.dae"
File access (Error): Critical error: ERROR_COULD_NOT_OPEN_FILE Additional: F:\depot\mwo\objects\mechs\bloodasp\body\bloodasp.dae
The Collada import has been forced to stop.
Please fix the reported error and then try again.COLLADAFW::Root::loadDocument() returned false on 1st pass
+----------------------------------
| Collada Import : FAIL
+----------------------------------
Error: Parsing errors in Document (see Blender Console)
Error importing armature at: F:\depot\mwo\objects\mechs\bloodasp\body\bloodasp.dae
________________________________

**Comment by Markemp** [comment]
Can you link that `bloodasp.dae` file here too please?  Just verified on mine that it was able to load, so curious as to why it errored here.

**Comment by Dakkapocalypse** [comment]
________________________________

**Comment by Dakkapocalypse** [comment]
Actually, that might be the problem -- there is no bloodasp.dae file that I can find.

________________________________

**Comment by Dakkapocalypse** [comment]
[cid:44fdf8ea-0772-4942-9b02-8faf986f05d4]
________________________________

**Comment by Markemp** [comment]
Can you try to convert just that single file with cgf-converter?  If it fails, then post the output please.

**Comment by Dakkapocalypse** [comment]
Sure, I'll get that done tonight and send the result.

________________________________

**Comment by Dakkapocalypse** [comment]
I went through the tutorial and did the exact same file that you did (the rasalhague medalion), and it created the .dae file just fine.

So it has to be something with the command line that I'm using

________________________________

**Comment by Markemp** [comment]
The `objectdir` argument looks off.  You have it as `-objectdir F:depot\mwo`, but there should be a backslash after the F:.  Not sure if that is the root cause though.  The bloodasp.chr file should convert to the dae file without the objectdir argument.

**Comment by Markemp** [comment]
Any update on this?
