### ISSUE TITLE
Program 'cgf-converter.exe' failed to run: The specified executable is not a valid application for this OS platform.

### ISSUE THREAD

**Issue by vemeT5ak** [Markemp/Cryengine-Converter#124]
Before I start digging out an old rusty, Any idea what may be the cause, aside from Windows 11, of this error?

Program 'cgf-converter.exe' failed to run: The specified executable is not a valid application for this OS platform.At
line:1 char:44
+ ... m *.cga)) { .\cgf-converter.exe $file -allowconflict -objectdir "C:\M ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:44
+ ... m *.cga)) { .\cgf-converter.exe $file -allowconflict -objectdir "C:\M ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

I'm running a fully patched windows 11.

**Comment by vemeT5ak** [comment]
No idea what windows is doing, later attempts worked, ish.

**Comment by Markemp** [comment]
Thanks for the update.  Looks like for some reason it couldn't find the program at first.  Glad it's working now!
