### ISSUE TITLE
Crysis (2007) error on .chr files

### ISSUE THREAD

**Issue by Voikanaa** [Markemp/Cryengine-Converter#131]
**Describe the bug**
Original Crysis .chr models throw an error. Applies to all .chr files I've tested so far.

**Sample Model with the issue**
- Crysis (2007)
- Objects/Characters/Human/US/Marine/Marine.chr

**Screenshots**
![error_chr](https://user-images.githubusercontent.com/110537207/182608762-45981c0c-b118-4629-b3f0-48a0b5408892.jpg)

**Additional context**
- Working fine with .cgf files so no typos in cli.
- Noesis and old CryEngine plugin didn't work.

**Comment by Markemp** [comment]
Sort of have it figured out, but for some reason the armature is rotated 180 degrees.  You will need to do some manual cleanup:

- Put armature into edit mode.
- Rotate all bones 180 degrees around the z axis
- Move the bones slightly along the y axis to line up with the model.

![image](https://user-images.githubusercontent.com/12057128/194760597-5028e051-9a12-43a4-863d-7180c2da9734.png)

**Comment by Markemp** [comment]
Will be releasing 1.4.0 this weekend with these changes.
