### ISSUE TITLE
Normals ( or Smoothing groups? ) didnt correct.

### ISSUE THREAD

**Issue by mortany** [Markemp/Cryengine-Converter#136]
**Describe the bug**
Exported smoothing dont original, because normal map dont aplly correctly with this smoothing. I tried .dae and .obj and got same wrong result.

Game: Sniper Ghost Warrior Contracts 2
Model: objects.pak\objects\weapons\ksg_pc33\ksg_pc33_fp.chr

![image](https://user-images.githubusercontent.com/18101486/186389972-3e5e85e2-55bf-4177-bc44-f6ef7f076a9b.png)

**Comment by mortany** [comment]
Ah, its mistake, its fixed after swap X and Y channels in normal map.

**Comment by Markemp** [comment]
Quick question before closing this officially:  Did you have to manually swap that out, change the game file's normal map, or something else?  I want to make sure that the mapping isn't wrong in the code even if there was a manual fix.

**Comment by mortany** [comment]
> Did you have to manually swap that out

Yep, texture has DXGI_FORMAT_BC5_SNORM format and after save it into tga i swapped red and green channels and smoothing after apply normal map looks absolutely correct like as ingame. Normal vectors looks correct in my opinion.

**Comment by mortany** [comment]
![image](https://user-images.githubusercontent.com/18101486/186614787-6e19795a-0a53-471c-998b-2929857acc04.png)
