### ISSUE TITLE
Star Citizen: Glaive model "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by scorg-tools** [Markemp/Cryengine-Converter#137]
Extracting the Glaive model (Data\Objects\Spaceships\Ships\VNCL\Glaive\VNCL_Glaive.cga) from Star Citizen, running via StarFab export., gives the following error:

VNCL_Glaive: ERROR: model conversion failed for G:\StarCitizenTools\game-data\Data\Objects\Spaceships\Ships\VNCL\Glaive\VNCL_Glaive.cga: 

********************************************************************************
There was an error rendering G:\StarCitizenTools\game-data\Data\Objects\Spaceships\Ships\VNCL\Glaive\VNCL_Glaive.cga

Object reference not set to an instance of an object.

   at CgfConverter.CryEngineCore.ChunkBoneNameList_745.Read(BinaryReader b)
   at CgfConverter.CryEngineCore.Model.ReadChunks(BinaryReader reader)
   at CgfConverter.CryEngineCore.Model.Load(String fileName)
   at CgfConverter.CryEngine.ProcessCryengineFiles()
   at CgfConverterConsole.Program.Main(String[] args)

**Comment by Markemp** [comment]
Found a weird bonename structure for this model.  Got a fix and it seems to be working for the geometry, although I don't see the armature.  Will try to sort that out, but until then...

![image](https://user-images.githubusercontent.com/12057128/194589095-bca0fad5-1262-426f-9f9c-61b370ec13bf.png)

**Comment by scorg-tools** [comment]
Thanks @Markemp, I know a few people who's only missing ship is the Glaive, will be great to get this rendered to finish the whole lot!
Thanks for the great tool!

**Comment by Markemp** [comment]
Closing issue.
