### ISSUE TITLE
„The object reference was not set to an object instance.“?

### ISSUE THREAD

**Issue by Till17** [Markemp/Cryengine-Converter#14]
Tried it per PM already - probaly a noob problem: 
I unpacked a copy of my (than) SC 3.0.1 build with the SCLeaksP4KBuster. It worked pretty good and looks right [saved in D:\Depot]. Than I downloaded your gf-converter.exe, did put it in the directory D:\scripts and modified the path in the advanced system settings [D:\scripts].

Trying to convert some single Constellation-files took me many hours on several evenings, but I didn' get it working. Most probably the problem is sitting in front of the screen.

Copying the .cga or .cgam files into the directory and drag'n dropping them from there in the explorer only makes opening and closing a littele black window for 0.1 sec.

Typing in power shell only produces this cryptic (to me) failure massage:

„The object reference was not set to an object instance.“ (in German: „Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.“)
image: http://www.alphaforge.de/sc/error_ggf-converter.png

I have no idea, what to try now. Can you or somebody here help me?

best regards

**Comment by Markemp** [comment]
There seems to be a problem with the converter on the Constellation file.
I'm going to take a look and see what I can figure out is going on, but it
may be a few weeks before I can get this fixed.


https://gyazo.com/373851138588f330bbc08c8a75396e53

**Comment by Till17** [comment]
Seems to have been a problem with my powershell-command, got it running now. Don't actually know why... ;-)

**Comment by Markemp** [comment]
Closing the issue as it's resolved.
