### ISSUE TITLE
Animation export support

### ISSUE THREAD

**Issue by Soreepeong** [Markemp/Cryengine-Converter#145]
I've been working on ChunkController905 support (implemented [this](https://github.com/Soreepeong/Markemp-Cryengine-Converter/commit/c95a6b4da2793e44bbffb812e7b0890a9bd4a38d) from [this](https://github.com/aws/lumberyard/blob/413ecaf24d7a534801cac64f50272fe3191d278f/dev/Code/Tools/RC/ResourceCompilerPC/CGA/TrackStorage.cpp#L614-L1132)), and seems that we can obtain the list of tuples of (animationName, controllerId=bone, time, optional<translationalVector3>, optional<rotationalQuaternion>).

The problem is that when I wrote to library_animation in collada file, Blender just won't load the animation. I forgot to commit the wip yesterday so code isn't there (will do that later), but just wanted to ask if you got some pointers on exporting animations, in case you have tried that before.

**Comment by Markemp** [comment]
I haven't looked at animations before but did dig into the collada docs for it a while back.  Blender's implementation of Collada is generally pretty good, but it can get weird some times.

One thing you might want to try is to create a simple model with a couple of bones, add an animation, and then export that file to Collada.  It should create the `library_animation` for you, and then you can compare it to what your animation output looks like to see if there are any differences.

I've been working on adding USD support to the project, which seems like the way forward too.  It appears to be the de facto standard.  It's been challenging to get it to compile.  And I really need to compile it with the `/clr` option so that I can use the dlls directly in the project (or ideally, make a Nuget package so it's available to everyone).  I don't suppose you have any experience compiling c++ projects into the common language runtime? :)

**Comment by Soreepeong** [comment]
I was trying to integrate FBX SDK with it but lost interest for the day when designing structures for interops, referring to https://github.com/lmcintyre/fbxInterop and https://github.com/TexTools/TT_FBX_Reader . Easiest way would be just dllexporting the functions.

Blender couldn't import the collada file exported from Blender correctly for a complicated one, so I'm starting with this instead: https://gist.github.com/sbarthelemy/610049/a4ee9e6c33af901001aecf1ba61b08a82d4ea40f

**Comment by Soreepeong** [comment]
It kind of works, but seems that a lot of rotational quats are getting dealt w.r.t. wrong axis. Judging from the connecting part between head and "hair" have distinct border between them, maybe something about model exporting has to be fixed?

https://user-images.githubusercontent.com/3614868/203582998-5653b703-2e43-4dd0-aa77-186cabb48ebb.mp4

**Comment by Markemp** [comment]
I am fairly confident that cgf-converter doesn't handle rotations correctly.  It just happens to get it wrong in just the right way where it works most of the time, but I think I'm still missing something.  :(

I'm going to poke around in this space too after the holidays and see if I can help you with the animations.  That would be a huge win!  Thank you for doing so much ground work on this.

**Comment by Soreepeong** [comment]
I'm actually implementing a Blender exporter that exports a python script that shall be run inside Blender - got mesh import done for now, and immediately got stuck on what info from the chunks are the "head" and "tail". Anyhow exporting a script would definitely be easier than making a Blender save file ourselves!

**Comment by Soreepeong** [comment]
https://github.com/Soreepeong/Markemp-Cryengine-Converter/tree/chunkcontroller905

[wiiu-things.zip](https://github.com/Markemp/Cryengine-Converter/files/10081447/wiiu-things.zip)

Animation quat directions are... strange. Just sharing what I've done so far if you feel like tackling at it at a later time!

**Comment by Markemp** [comment]
Oof... this is complicated.  Your 905 controller is pretty amazing.  I'm having a hard time figuring out all the animation basics, but still plugging away at this.

**Comment by Soreepeong** [comment]
I pretty much let it go for the time being; I can get the animation to play okay if all vertices are manually relocated every animation frame but couldn't figure out how to export it into values that blender or gltf would accept correctly.

**Comment by Markemp** [comment]
Do you mind if I import your updates into my project and do some testing?

**Comment by Soreepeong** [comment]
Of course not! Feel free to go ahead.

**Comment by stixsti** [comment]
Hello, I was curious if there were any updates to this as exporting Cryengine animations is really exciting to me!

**Comment by Markemp** [comment]
Been sidetracked on a couple of other projects.  It's still on my high priority list though!

**Comment by Dizcordum** [comment]
*Waiting patiently*

**Comment by Markemp** [comment]
I know. :)  Been busy with a few other projects.  It's still next on my list though.

**Comment by Dizcordum** [comment]
> I know. :) Been busy with a few other projects. It's still next on my list though.

.caf animations convert is musthave

**Comment by Soreepeong** [comment]
Just in case - do let me know if any of my code is confusing while working on it!

**Comment by Dizcordum** [comment]
Any update on animations support? : )

**Comment by Soreepeong** [comment]
It's done; you just have to compile it yourself until a new release happens. Also note that it has a high chance of not working if not for Rise of Lyric.

**Comment by Soreepeong** [comment]
The master branch.
