### ISSUE TITLE
"Index was outside the bounds of the array"?

### ISSUE THREAD

**Issue by Expanix** [Markemp/Cryengine-Converter#15]
I'm not really sure if I'm doing something wrong, but since I don't know anything about C#, I'm having issues figuring out what the problem is.

I've been trying to convert some Evolve models to Collada files, and since there are no .cgf files, I just rename the .skin files, because if I don't, I get the "Object reference not set to an instance of an object" error someone commented below. The weird thing is, for some models it works properly, but when converting most of them, I get this error:

********************************************************************************
There was an error rendering C:\Users\User\Desktop\TodasLasCarpetas\User\SFM\EvolveModels\Bucket_Raw\bucket.cgf

Index was outside the bounds of the array.

   at CgfConverter.COLLADA.WriteLibrary_Controllers()
   at CgfConverter.COLLADA.Render(String outputDir, Boolean preservePath)
   at CgfConverter.Program.Main(String[] args)
********************************************************************************

Also, this only happens when I try to export the file as .dae; when I export it as a .obj it outputs a "blank" object.
Am I messing something up? Or is it just that it doesn't support those .skin files after being converted? If that was the case... none of the models would work, right?

**Comment by Expanix** [comment]
I'm pretty sure it is not a missing file issue, since I got them directly from the game devs (they left a link with a lot of stuff in it). A thing I have realized is that the .skin files come along with .skinm files, and I have noticed that the ones that don't work are the ones whose .skin file is smaller than their .skinm one. (I'm not 100%, but it is that way for what I have seen).

What could this mean?

I'm leaving you a Drive folder with basically all the stuff you need, so you can do what you see convenient: https://drive.google.com/drive/folders/0BxDJEP7XGdbAS1pPU2ZDeWhUbWc

**Comment by Markemp** [comment]
The .skin/.skinm (and .cga/.cgam along with other old file extension) is the new way of Cryengine handling the data.  The m file has the geometry info, and the .skin file just has basically header info.  In almost every case, the .skin file should be smaller than the .skinm file.  It's possible that the animation data (and armature?) is in the .skin file, but.. it's been a while since I looked.

Thank you for the files.  Were there any .mtl files in that folder as well?  Those are needed to make sure that the converter can create the proper materials.

**Comment by Expanix** [comment]
Yes, there were .mtl files in that folder, and I'm sure I'm using the -objectdir command properly.
If the .skin file is just header info, why does it only work with .skin files that are bigger than the .skinm ones, only when they are renamed to .cgf? It's really odd.

**Comment by Markemp** [comment]
The latest updates seem to be working a lot better.  I've tested a few of the griffin files (skin and chr), and they seem to be working.  Closing out this issue, but if there are still some problems let me know and I'll take a look.
