### ISSUE TITLE
Error rendering Armored Warfare

### ISSUE THREAD

**Issue by KIRkatastrofa** [Markemp/Cryengine-Converter#163]
Game: Armored Warfare
Models: t-62_turret_t-62.cgf (as an example)

I'm trying to convert a model in *.cga, .cgf format to .due format

![Error](https://github.com/Markemp/Cryengine-Converter/assets/82763989/2523031c-2fc4-4b11-adcc-8a9e8e4b6c73)

Please help me to solve this problem

**Comment by Dizcordum** [comment]
send file here

**Comment by Markemp** [comment]
Can you include the `-objectdir` parameter in the command?  Based on your layout, it should probably be `-objectdir d:\modelsCryEng\AWTank\`.

**Comment by KIRkatastrofa** [comment]
I tried this too, unfortunately it didn't work.
![screen](https://github.com/Markemp/Cryengine-Converter/assets/82763989/12f5c160-137d-4c8a-a58d-31fc813e0834)

**Comment by Markemp** [comment]
Just checked this with the preliminary 1.6 release and it looks like it's fixed.  AW uses the split dds files, which is annoying, but at least they can be unsplit.

**Comment by KIRkatastrofa** [comment]
for some reason it didn’t help, but I found a way to get around it. Thanks :)

**Comment by Markemp** [comment]
Can you give me some more info about why it didn't work?  Did you build the 1.6 release and use that to test the models?  Or how did you find a way around the error?
