### ISSUE TITLE
Icarus Online model issues

### ISSUE THREAD

**Issue by Tosyk** [Markemp/Cryengine-Converter#19]
game: Icarus Online

I had failed to convert a model. It's a hand model (hm_inner_04.chr).
Though all the files (except this one) I tried are working so far.
I attached some models that works for the reference.

********************************************************************************
There was an error rendering D:\_r\icarus_online_pc\_r2017_11_28\objects\
characters\players\hm\hm_inner_04.chr

Index was outside the bounds of the array.

at CgfConverter.COLLADA.WriteLibrary_Geometries() в C:\Users\Geoff\Source\Repo
s\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 633
at CgfConverter.COLLADA.Render(String outputDir, Boolean preservePath) в C:\Us
ers\Geoff\Source\Repos\cgf-converter\CgfConverter\Renderers\Collada\COLLADA.cs:line 91
at CgfConverterConsole.Program.Main(String[] args)
********************************************************************************

here's files:
[icarus_hm.zip](https://github.com/Markemp/Cryengine-Converter/files/2649608/icarus_hm.zip)

**Comment by Markemp** [comment]
Just checked against the Icarus files provided here.  It's able to convert them now (1.0.5 release, which will be coming out soon). :)
