### ISSUE TITLE
MWO *.chr not working correctly

### ISSUE THREAD

**Issue by madMAx43v3r** [Markemp/Cryengine-Converter#191]
**Describe the bug**
When I try to convert a MWO mech from *.chr it only gives me a lot of dots in blender. Some mechs don't have any *.cgf file, so this would be the only way...

**Sample Model with the issue**
- MWO
- Objects\mechs\highlander\body\highlander.chr

**Screenshots**
![image](https://github.com/user-attachments/assets/87fa346e-fd11-4a14-91a9-69c10f7b0f6a)

**Additional context**
Maybe user error?

**Comment by Markemp** [comment]
The .chr file is the armature, so those dots represent the bones for the mech.  My Cryengine Importer project can take that along with all the mech parts under the body dir and assemble it properly.  

You might want to watch my cryengine converter videos on Youtube.  It goes over how to convert all the objects for a mech and then assemble them.  https://www.youtube.com/playlist?list=PL106ZeLhxxVn551_IKGKeU_LBODtkh29b
