### ISSUE TITLE
Archeage models

### ISSUE THREAD

**Issue by sunkhaskasis** [Markemp/Cryengine-Converter#20]
~~I know I've already messaged you about this on reddit, but I figured I should leave this here too. 

It looks like the converter does not support Archeage models (Cryengine 3). When trying to convert a `.cgf` file, it outputs the following error:
```
Object reference not set to an instance of an object.

in CgfConverter.COLLADA.WriteLibrary_Effects() in C:\Source\Repos\cgf-converter\CgfConverter\Renderers\Coll ada\COLLADA.cs:line 405 in CgfConverter.COLLADA.Render(String outputDir, Boolean preservePath) 
in C:\Source\Repos\cgf-converter\Cgf Converter\Renderers\Collada\COLLADA.cs:line 89 in CgfConverterConsole.Program.Main(String[] args)
```
^^^^^^^^^^^^^ RESOLVED ^^^^^^^^^^^^^

Trying it on a `.chr` file displays this:
```
Version 801 of ChunkCompiledBones is not supported

   in CgfConverter.CryEngine_Core.Chunk.New[T](UInt32 version) in C:\Source\Repos\cgf-converter\CgfConverter\CryEngine_Core\Chunks\Chunk.cs:line 0
  in CgfConverter.CryEngine_Core.Model.Read_Chunks(BinaryReader reader) in C:\Source\Repos\cgf-converter\CgfConverter\CryEngine_Core\Model.cs:line 292
   in CgfConverter.CryEngine_Core.Model.Load(String fileName) in C:\Source\Repos\cgf-converter\CgfConverter\CryEngine_Core\Model.cs:line 180
   in CgfConverter.CryEngine..ctor(String fileName, String dataDir) in C:\Source\Repos\cgf-converter\CgfConverter\CryEngine\CryEngine.cs:line 59
   in CgfConverterConsole.Program.Main(String[] args)
```

Again, I know you're aware of this because of my reddit message, but on Xentax forum I saw people asking about AA models too, so I'm opening the issue here. Feel free to remove/close it if you're already working on it. It may actually be me using the `-objectdir` command wrong.

Here's the sample if you'd like to test it out yourself:
https://ufile.io/hqrz98wj
EDIT: I've added another sample for convenience:
https://ufile.io/eispk0ym

**Comment by MiracleBlessing** [comment]
Figures. I haven't really tried using the converter with files other than those I've provided to be honest because after trying it on them, I thought it doesn't work on AA at all.

**Comment by MiracleBlessing** [comment]
Update: With the release of the new version, the .cgf files work perfectly, but unfortunately the .chr file still outputs a 801 chunkbones error.

**Comment by Markemp** [comment]
I'm installing ArcheAge now to see if I can figure out the bones issue.

**Comment by Markemp** [comment]
Hmm... can't extract the pak file.  If anyone has a .chr file I can look at, that would help.

**Comment by MiracleBlessing** [comment]
https://github.com/ZeromusXYZ/AAEmu-Packer/releases/download/v0.6.2/AAPakEditor-20191130-v0.6.2.zip try using this

**Comment by MiracleBlessing** [comment]
I saw you doing some tests with AA models recently, but unfortunately a .chr files still outputs a 801 chunkcompiledbones error

**Comment by FlameSoulis** [comment]
Can confirm the CHR files are still an issue. However, using Noesis, the models can be read just fine but not the skeleton. It'll be interesting to see if this can be resolved or looked into, but no rush.

**Comment by Markemp** [comment]
Been doing some research on this.  Archeage uses different compiledbone models (0x0801) than other games.  The size of the bone models is 324 bytes instead of ...500something.  Source code for both Cryengine and Lumberyard don't recognize a 0x0801 version of CompiledBone objects, so I have to see if I can reverse engineer it.  There is another bone related chunk that also uses an unsupported version.  Fun. :|

**Comment by Markemp** [comment]
@peter-dolkens while working on the new bone models, I think I ran across a bug in the BinaryReader extension ReadFString(). 

```
            //_ = b.ReadFString(208);                 // Unknown for now
            b.BaseStream.Position = b.BaseStream.Position + 208;
```

This is in my Structs.cs class (ReadCompiledBone_801 method) in the dump-chunks branch.  On the 6th iteration through a loop reading the bones in an Archeage model (coupleduckship_foot.chr), ReadFString(208) moves the position 209 bytes.  It's a really weird situation and I was wondering if you can take a quick peek to see if I'm taking crazy pills here.  Only thing I can think of off the top of my head is that the conversion between long and int just doesn't work right in this one situation.

(I know, I'm not using the method properly.  I shouldn't be trying to read a string here, and instead am just trying to move the pointer ahead 208 bytes.  Still weird that it's moving 209 bytes though).

Model can be found at https://1drv.ms/u/s!Ahz_oM1_DqLRkIRpInHnr5OXLAalRw?e=adWcgt.

**Comment by Markemp** [comment]
I've figured this out, and the next release should support new Archeage .chr models, complete with skeletons. :)

**Comment by Markemp** [comment]
ArcheAge should be working now (aside from some armature issues in some chr or skin files).  Closing this issue, but if you find some models that aren't working, please open a new issue for those.  Thank you!

**Comment by shirator** [comment]
For some reason the latest version isn't working anymore?

**Comment by Markemp** [comment]
Can you provide some additional info?  Which version of the Converter are you using, and which model in ArcheAge?

**Comment by Sovets500** [comment]
heyy!! i would like to use this to converter some .CHR to blender(dae or smt) but i'm in trouble can u help me?

**Comment by Markemp** [comment]
Can you provide a bit more details on what's not working?
