### ISSUE TITLE
Doesn't work with Sonic Boom: Rise of Lyric assets, maybe.

### ISSUE THREAD

**Issue by AnotherBlob** [Markemp/Cryengine-Converter#24]
I guess this doesn't work with Sonic Boom: Rise of Lyric assets yet because it resulted in this error.
![who is geoff](https://user-images.githubusercontent.com/32704565/67159479-7b64b000-f345-11e9-84ee-0dd76c31881c.png)
I'll have to rely on CryEngine to export models for now...

**Comment by Markemp** [comment]
Yup, looks like another custom chunk issue. I don’t have the game files available to test these. 😟

**Comment by AnotherBlob** [comment]
> Yup, looks like another custom chunk issue. I don’t have the game files available to test these. 😟

Oops, I only saw this answer today. Sorry! I'd gladly send over some files then. Do you have an email address or something?

**Comment by nanogram** [comment]
Sonic Boom data extraction doesnt work me either rip

**Comment by MisterSlocker** [comment]
yo i have the extracted files

**Comment by MisterSlocker** [comment]
> Yup, looks like another custom chunk issue. I don’t have the game files available to test these. 😟

i can hook you up

**Comment by Markemp** [comment]
That would be handy.  Thanks!

**Comment by MisterSlocker** [comment]
> That would be handy.  Thanks!

do you have discord? id like to message you there as its quicker, and im more active on there. but ill send you the files, how would you like to recieve them?

**Comment by MisterSlocker** [comment]
wanna talk somewhere else? ive got the files ready to be sent over

**Comment by Markemp** [comment]
I'm not on Discord, but feel free to paste a link to a shared drive like Google or OneDrive.  I can get the models from there.

**Comment by MisterSlocker** [comment]
Would you like the whole Game dump? its around 9GB, or do you want a part of the dump with some models (.cgf files )to test on?

**Comment by Markemp** [comment]
I just need a couple of models to inspect.

**Comment by Markemp** [comment]
I'm ... not really comfortable with discussing this here.  Technically sharing the models could get the project in legal hot water.  Let me check to see if there is another way I can get the info I need.

**Comment by MisterSlocker** [comment]
> Yup, looks like another custom chunk issue. I don’t have the game files available to test these. 😟

well according to your older comment, you said it looks like a next custom chunk issue. i have the models, so if theres anything i can do to contribute let me know.....

**Comment by peter-dolkens** [comment]
Heffay - I think I made my socpak branch dump the extra chunks instead of crashing - we could make this the default behaviour for unknown chunks. No lost data, and if there's a bug to report, people could attach the individual chunks.

Peter Dolkens

**Comment by Markemp** [comment]
I'll take a look at what you did there and move it over to the main branch.  Getting some sort of logging for missing chunks that could be sent up would be awesome too.  Would save so much time trying to track this stuff down.

**Comment by peter-dolkens** [comment]
Hmm, just checked (was on mobile earlier) - doesn't look like I checked in the code to dump the chunks - only the one I had a serializer for (embedded CryXmlB)

**Comment by MisterSlocker** [comment]
do i guess my models/game dump are no longer needed then?

**Comment by Markemp** [comment]
I'm going to work on an update where, if it runs into stuff it doesn't recognize, it doesn't just blow up.  And instead it can send just those missing chunks up so that they can be analyzed and added much more easily.  I probably won't be able to get started on this until next weekend though.

**Comment by MisterSlocker** [comment]
alright, cant wait as im really trying to dump those stage models from sonic boom

**Comment by Markemp** [comment]
This seems to be a console game that has a different Endian strategy than other games.  I'll see if there is a way to convert the geometry models if it isn't too much work.  But it may be that platforms with CPUs that use a different endian strategy than the PC might be out of scope of this project.

**Comment by Markemp** [comment]
![image](https://user-images.githubusercontent.com/12057128/103010764-0d41ed00-44f6-11eb-9177-eb62c95b98cb.png)

I think I got it, but doing some more testing.

**Comment by MisterSlocker** [comment]
thats the sonic boom rise of lyric checkpoint model if anyone doesnt realize😅.

But nice work, let me know if anything else is required

**Comment by Markemp** [comment]
Nope, should be good.  You can remove the files from google drive if you want.  I should have an official release ready by the end of the weekend.  Thanks again for your help!

**Comment by Markemp** [comment]
And by the end of the weekend, I mean the end of next weekend.... :|

**Comment by MisterSlocker** [comment]
alr take ur time bro

**Comment by AnotherBlob** [comment]
That's still amazing, thanks!

**Comment by MisterSlocker** [comment]
is the update out

**Comment by Markemp** [comment]
Just released this now.  Sorry for the delay!

https://github.com/Markemp/Cryengine-Converter/releases/tag/v1.0.8

Let me know if you run into any issues.
