### ISSUE TITLE
converting .cgf

### ISSUE THREAD

**Issue by CrimsonMiralis** [Markemp/Cryengine-Converter#27]
i'm having an error trying to convert a .cgf file from my game. 
cgf-converter.exe -dae forest_ruin.cgf -noconflict
is the command that i've been trying, also attempted with -obj instead of dae
The error I end up with is 
"There was an error rendering forest_ruin.cgf", 
"Object reference not set to an instance of an object. 
       at CgfConverterConsole.Program.Main(String[ ] args)"

[forest_ruin.zip](https://github.com/Markemp/Cryengine-Converter/files/3894334/forest_ruin.zip)

**Comment by Markemp** [comment]
I'll take a look at this soon.

**Comment by Markemp** [comment]
https://gyazo.com/aeb48aeee0763f094a2838d5c722e380

I've made some changes to the program that may help, but it does look like your .mtl file isn't an actual Cryengine mtl file.  Or at least not any format I've run across yet.  Can you provide some more info about what that file is about?

I'm adding a couple of other bug fixes to the program, but will have a new release pushed out in a day or two.

**Comment by Markemp** [comment]
Closing this issue.
