### ISSUE TITLE
Flag not updated on help page

### ISSUE THREAD

**Issue by draakuns** [Markemp/Cryengine-Converter#28]
Hi,

I am using this tool for SC, and as DDS on that game are split into several files and unsupported I went down the road converting to TIF. The point is that you must also use the -tif flag when converting the files,  but it doesnt appear on the help page.

Can you add it to avoid more ppl having the same doubts as I had if you see fit?

Thanks!
Draakuns

**Comment by Markemp** [comment]
Updated the args to include the -tif option.  This will be updated in the 1.0.5 version coming soon. 
 Thank you for the feedback!

**Comment by draakuns** [comment]
Sorry mate, I've been quite busy these days... thanks a lot!
