### ISSUE TITLE
Collada files being overwritten by same name cgf and cga files

### ISSUE THREAD

**Issue by draakuns** [Markemp/Cryengine-Converter#29]
Hi,

here I will try to merge 2 issues/doubts to try to reduce my noise.

- Is your tool currently managing separate cga+cgam, cgf+cgfm, etc?

- I see that you use a Powershell command to batch convert all cga, cgf, chr & skin extensions. On my case, a directory holds a file "test.cga" + "test.cgam", and creates a DAE file. But the problem comes when it also holds a "test.cgf" + "test.cgfm", because the previous DAE file gets overwritten, as same output name applies "test.dae".
Am I missing something there, or there's no way to use under that condition? Or maybe I am wrong and it merges everything into the same DAE file?

Thanks in advance,
Draakuns

**Comment by Markemp** [comment]
It will combine a .cga/cgam pair into a single model, as they are related.  If you put in a file with the m extension, it should skip over that and not try to reprocess it.  Or at least that is the way it *should* process.  In the event putting in a .cgam file causes it to reprocess, just filter out those files in the Powershell script when you are doing a batch run (i.e. just have it work on cga, cgf, skin and chr files, and not their m counterparts).

**Comment by draakuns** [comment]
Ok, so then the cga/cgam bulletpoint is clear... but what happens when it needs to convert a CGA and a CGF with the same basename on the same path? Are they merged together? 
From what I can see, the last one just overwrites the previous :(
Maybe it's expected, but on SC it completely breaks the conversion. Yeah, i know that SC support is on hold until gold, but just trying to sort out things.

Thanks!
Draakuns

**Comment by Markemp** [comment]
If a file has both a cga and cgf version (ship.cga and ship.cgf), then whichever is last converted will be converted to the .dae file.   .cga files should have the full models, plus animation files.  I'm not sure why they would have duplicate file names like that though.  If you can convert one, check out the geometry, then convert the other and compare it to the first file, I'd be really interested to know what the differences are.

**Comment by draakuns** [comment]
Hi,

Honestly I was not expecting having that files splitted, and in that case I was confident that the conversor would be "expecting" that... Sorry but I am completely new to Cryengine.

Will do and will post the results that I am able to get. What I can tell you in advance is that the files are different size if converting cga or cgf (or chr or skin).

If thats ok for you I will try: 
1. cga+cgf on the same dir.
2. cga only on the dir.
3. cgf only on the dir.
4. maybe having one dae file already there, then copying the other filetype (cgf for instance), and converting again (just to check what happens and cover all casuistics...)

Will keep you posted!
Draakuns

**Comment by draakuns** [comment]
Hey, sorry for the delay. I will hopefully update this now that #33 is fixed, as a week ago I tried but some DAE files were missing due to the objects failure introduced on v1.0.5.

Thanks for your patience on all aspects!
Draakuns

**Comment by Markemp** [comment]
Closing this.  If it's still an issue, let me know and I can reopen it.
