### ISSUE TITLE
Enable Converter to write existing Vertex Color data + include Physics Proxy mesh

### ISSUE THREAD

**Issue by WoodyChuckHub** [Markemp/Cryengine-Converter#31]
Some Cryengine assets depend heavily on painted Vertex Color data. e.g. vegetation assets that use detail bending based on RGB painted vertex color. 
Atm exported meshes do not contain any vertex color set in them and it would be very helpful if they would.
[https://docs.cryengine.com/download/attachments/24285894/final_blend.jpg?version=2&modificationDate=1473087581000&api=v2](url)
Assets in question e.g. would be the GameSDK samples that come with Lumberyard. e.g. trees, palm trees coming from the old GameSDK, the original assets dating back to Crysis times even but then were converted for CE3.

Another addition that would be super helpful would be to include the physics proxy mesh.
Atm programs like NinjaRipper can include the physics proxy if a Cryengine user has switched to "show Proxies" before ripping, but getting those proxies found and sorted in the mess that is NinjaRipper .rip files is more than cumbersome!

These 2 additions would make Converter a complete tool to use!
Thank you so much for working on this tool in the first place!
Cheers!

**Comment by Markemp** [comment]
I've seen vertex color data in the Cryengine files.  I'll have to check to see if Collada supports vertex color.  I'm pretty certain it does and should be able to get it added.

**Comment by Markemp** [comment]
Do you have an example file I can look at?  That plant model you posted on Xentax would be perfect.

**Comment by WoodyChuckHub** [comment]
some examples, these are from Lumberyard Woodland asset pack and GameSDK
[palmtree.zip](https://github.com/Markemp/Cryengine-Converter/files/4539301/palmtree.zip)
[bushes.zip](https://github.com/Markemp/Cryengine-Converter/files/4539299/bushes.zip)

**Comment by Markemp** [comment]
Can you test out the color data using this build?  Blender doesn't seem to handle importing vertex colors in Collada very well, so I'm not sure if it's working properly or not.

https://github.com/Markemp/Cryengine-Converter/releases/tag/v1.0.6

**Comment by WoodyChuckHub** [comment]
Hey markemp

It seems that pre-release converter.exe is doing something with vertex color. some assets now have a vertex color set listed after import, but that color is looking wrong/faulty and a lot of meshes are often exploded with some warning messages now, which they did not do before.
Some meshes like the twisted tree still looked "correct" but a lot of others I tested with did not.

![dae_vertexcolor_twistedtree](https://user-images.githubusercontent.com/61787830/80952203-9be3eb80-8df9-11ea-9268-9f1f191cafca.JPG)

![dae_vertexcolor_ground_cover_fern_a](https://user-images.githubusercontent.com/61787830/80952196-9a1a2800-8df9-11ea-89f8-ffeef623b8ae.JPG)
![dae_vertexcolor_palmtree](https://user-images.githubusercontent.com/61787830/80952198-9ab2be80-8df9-11ea-8046-59d9a0ddc666.JPG)

**Comment by Markemp** [comment]
![image](https://user-images.githubusercontent.com/12057128/81073521-9d1a2480-8e9c-11ea-84be-fac064d3793e.png)

Hmm... I think I got it.

**Comment by Markemp** [comment]
v1.0.6 release (latest official) now has vertex colors working.  Will start on the Physics Proxy Mesh now.

**Comment by Markemp** [comment]
Also, do you have a mesh with the physics proxy data?  Or is it also in the bush model?

**Comment by WoodyChuckHub** [comment]
Awesome will try this out soon. 
So Physics proxy data is normally inside of the .cgf itself. sometimes there are seperate LOD1,LOD2 render and proxy meshes for streaming reasons but proxy itself is always with the render mesh inside of the same .cgf

**Comment by drag-d** [comment]
Markemp, hello.
Are you still doing this project?
I can provide to you the test mesh with proxy meshes and vertex alpha.

**Comment by Markemp** [comment]
This should be fixed.  Checked it with the v1.6 release and it's good to go.
