### ISSUE TITLE
Fix rotation mode and W

### ISSUE THREAD

**Issue by Markemp** [Markemp/Cryengine-Converter#32]
To fix rotation in blender:
	- Select object.
	- Change Rotation Mode from XYZ Euler to Quarternion
	- Inverse W (so if .991, change to -.991).

Also look at making proxy material transparent for shields.

**Comment by Markemp** [comment]
Line 1122 in Collada.cs should maybe use [1] for the model instead of [0]?

**Comment by coloradocomputerpro** [comment]
Is it possible to systematically identify and delete the faces of which the proxy material is attached?

**Comment by peter-dolkens** [comment]
> [Line 1122 in Collada.cs](https://github.com/Markemp/Cryengine-Converter/blob/github-master/CgfConverter/Renderers/Collada/COLLADA.cs#L1122) should maybe use [1] for the model instead of [0]?

What about:
```
CryData.Models.SelectMany(m => m.NodeMap.Values.Where(a => a.ParentNodeID == ~0)).ToList()
```

Can we guarantee the important Model is always going to be [0] or [1]? Does it hurt us to process all of them?

**Comment by Markemp** [comment]
> > [Line 1122 in Collada.cs](https://github.com/Markemp/Cryengine-Converter/blob/github-master/CgfConverter/Renderers/Collada/COLLADA.cs#L1122) should maybe use [1] for the model instead of [0]?
> 
> What about:
> 
> ```
> CryData.Models.SelectMany(m => m.NodeMap.Values.Where(a => a.ParentNodeID == ~0)).ToList()
> ```
> 
> Can we guarantee the important Model is always going to be [0] or [1]? Does it hurt us to process all of them?

I'm going to give this a try.  Working on finishing some integration tests so that I make sure existing models don't break.  There may be an issue if the chuck IDs overlap between the .cga file vs the .cgam file, but not sure if that's ever really an issue.

**Comment by Markemp** [comment]
Got the instancing of geometry working again.  I couldn't use the SelectMany option.  I use model[0] to get the node and node object chunks, check to see if the object chunk is mesh or helper, and grab the appropriate geometry from model[1] if it's a mesh.  Seems to be ok for now.  Still testing.

**Comment by Markemp** [comment]
Closing as it seems to work ok.  Releasing v1.0.5 tonight.
