### ISSUE TITLE
StarCitizen ship models convert as series of empties

### ISSUE THREAD

**Issue by xbohov01** [Markemp/Cryengine-Converter#35]
Whenever using the tool to convert StarCitizen ship models from the 3.9.1 patch the result is just a cloud of points. Same result when I try to import with the cryengine-importer addon.

Steps to reproduce:
1. Extract ship assets
2. Convert with the tool
3. Import to blender

Expected result:
Ship mesh is imported.

Actual result:
Only empties are imported.

So I am not sure if this is a problem with the tool itself since every other model seems to convert 100% correctly or if it's the ship models themselves or if it's my workflow.

**Comment by Markemp** [comment]
Is this on all ship models? If not, can you let me know which models are failing to convert?

**Comment by xbohov01** [comment]
As far as I can tell it's all of them unfortunately

**Comment by xbohov01** [comment]
Tested this with the latest release. Most ship models seem to work great now! 
Some ships convert with simplified geometry on the standard model (LOD models are correct). Examples I found are the AEGS Avenger and DRAK Cutlass.
Seems to be isolated though, I checked about 30 other ships and they were fine so great fix, thank you!

**Comment by Markemp** [comment]
I've seen some ship models have a ... I don't know how to describe it.  Like a shield geometry structure slightly above the hard geometry, that ends up making it look low def until you get rid of it.  Can you check to see if there may be some weird external geometry/vertices, that if deleted show the expected model underneath?

**Comment by xbohov01** [comment]
I checked and you are right, there is a shield like mesh around the model and after deleting it the ship shows. Signed distance fields maybe?
Either way, thank you and good work! I think you can close the issue

**Comment by Markemp** [comment]
Will do, and thank you for the update!
