### ISSUE TITLE
Garbled Vertex Positions of .cgf Files 

### ISSUE THREAD

**Issue by Jaws-git** [Markemp/Cryengine-Converter#38]
Vertex positions come out wrong when trying to use the converter on Crucible cgf files. Different vertex bufffer offset/format?
Other file types might be affected? Couldn't try them out. 
Attached some sample input and output files.

![Cgf2DaeOutput](https://user-images.githubusercontent.com/22118709/97984415-0b518c80-1dd7-11eb-841f-ca16618f3066.png)

[CrucibleCgf.zip](https://github.com/Markemp/Cryengine-Converter/files/5481137/CrucibleCgf.zip)

**Comment by Markemp** [comment]
![image](https://user-images.githubusercontent.com/12057128/102735088-b8885180-42fe-11eb-9dd7-8782ebc2a0b6.png)

Got this figured out.  Will be pushing an update soon.

**Comment by Markemp** [comment]
Version 1.0.7 released to work with Crucible models. :)
