### ISSUE TITLE
Pandemic Express Extraction issue.

### ISSUE THREAD

**Issue by Sides404** [Markemp/Cryengine-Converter#40]
Unhandled Exception: "System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at CgfConverterConsole.Program.Main(String[] args)"
is what i get when attempting to extract the rebellion set models

**Comment by Markemp** [comment]
Will be looking at this soon.

**Comment by Markemp** [comment]
Can you provide a screenshot of the error when it happened?  Thanks!

**Comment by Sides404** [comment]
I seemed to fix it by installing https://dotnet.microsoft.com/download/dotnet/current/runtime and not the original runtime as intended Sorry for late response

**Comment by Markemp** [comment]
No worries.  Thanks for the feedback!  If this game gives you problems on any other models, please let me know.

**Comment by Sides404** [comment]
Alright
