### ISSUE TITLE
Converting CGF from aion

### ISSUE THREAD

**Issue by gabriel0220** [Markemp/Cryengine-Converter#46]
Hi!  
Is there an option to check, why converting files from AION is not working?
After i change the heading from NcAion to CryTek in Hex editor, the file is still cant be converted.

Thanks.

Link to the file.
https://mega.nz/file/YBRDxKhK#wKl13gZ4D-1_WYlztb7s45oEAw7IVXksN_09NMUltAM

**Comment by gabriel0220** [comment]
Hello. Still asking about it. Ive tried everything that i can and ask everywhere. No answer.

**Comment by Markemp** [comment]
I thought I got Aion models working.  Will double check this one.

**Comment by Markemp** [comment]
These don't appear to be Cryengine files.  There is no header table with the info needed to parse the data.  :(  

It seems to be an Unreal game.  This program isn't going to be able to convert it.

**Comment by neon-dev** [comment]
@Markemp it is a CryEngine game.
`FileSignature` is `NCAion` and `FileVersion` is 0x750.
Only difference with the file header is that `NumChunks` is located at the start of the chunk table.

**Comment by vmxeo** [comment]
fwiw, Aion uses a _highly_ customized version of Cryengine 1.
