### ISSUE TITLE
Newer SC .cgf files are not converting

### ISSUE THREAD

**Issue by Baconator650** [Markemp/Cryengine-Converter#49]
Star Citizen changed their .cgf files on their newer ships (Star Runner) and they do not output a .dae file. 

.cga files work fine.

**Comment by Markemp** [comment]
Can you check the file signature and see if those are now #ivo files too?

**Comment by Baconator650** [comment]
Not 100%, but think its showing CrChF as the file signature

**Comment by Baconator650** [comment]
Starter working after a system reset (not the first one) and starting to work now.

**Comment by Baconator650** [comment]
I am noticing that the newer cga and cgf files are not containing any material data and IDs.

**Comment by vmxeo** [comment]
@Baconator650 Make sure there's a corresponding mtl file in same folder as the asset you're converting.

**Comment by Baconator650** [comment]
that did, thanks

**Comment by Markemp** [comment]
Closing as this seems resolved.
