### ISSUE TITLE
Normals aren't correct for SC datastreams with 16 byte structures.

### ISSUE THREAD

**Issue by Markemp** [Markemp/Cryengine-Converter#5]
The normal part of the VertsUV struct seem to have been changed to Color, and the Normal is a calculated value from the Tangents datastream.  Need to calculate the correct normals from the Tangents datastream by taking the cross product of the tangent and bitangent.

**Comment by pixelpath** [comment]
To fix normals not displaying correctly in 3DS Max: Select the model and add an Edit Normal modifier to the stack. Now press CTRL + A to highlight all normals and click the Reset button in the Edit Normal modifier panel. Now the models explicit normals should be working.

**Comment by Markemp** [comment]
Thank you for the workaround!

**Comment by pixelpath** [comment]
No problem! I think by default, 3DS Max does not calculate normal relative to the surface and doing the reset forces it to rotate the normals relative to surface / tangent space but I am still trying to figure out the different normal modes. FWIW the 3DS Max SDK docs list some info on them that may shed more light on the situation: http://docs.autodesk.com/3DSMAX/16/ENU/3ds-Max-SDK-Programmer-Guide/index.html

**Comment by Baconator650** [comment]
The newer "weighted normals" produces a more accurate result.

**Comment by Markemp** [comment]
This has (finally) been resolved.  I think.  Closing the issue, but will reopen if necessary.
