### ISSUE TITLE
Which CryEngine versions does it support?

### ISSUE THREAD

**Issue by thealex626** [Markemp/Cryengine-Converter#51]
Hi! Please, tell me which CryEngine versions does this tool support? Is CryEngine 1 and 2 supported?

**Comment by Markemp** [comment]
Mostly Cryengine 3 stuff, but depending on the game files, it may be able to support some 1 and 2.  It really depends on which chunks they use.  Is there a particular game you are interested in?

**Comment by thealex626** [comment]
I'd like Crysis 1 and Far Cry 1 support too. Thanks!

**Comment by Markemp** [comment]
Going to close this issue as it is too generic.  If there are specific models for Crysis 1 or Far Cry 1 that don't work, please open an issue with the specific details.  The support for those older versions will probably be rudimentary (geometry only), but I'm not opposed to adding it when time permits.  Thank you!
