### ISSUE TITLE
Materials not found in locations other than current or parent folder

### ISSUE THREAD

**Issue by vmxeo** [Markemp/Cryengine-Converter#54]
It appears cgf files can reference material files in specific locations, however it appears cgf-convert only looks in the current or parent folder for a mtl file. If no materials are found, the  _library_materials_ within the DAE is then empty, and the file will fail to load in Blender with the following scheme error:
`Schema validation (Error): Error: ERROR_REQUIRED_ATTRIBUTE_MISSING Element: instance_material, Attribute: symbol, Line: 140, Column: 35, Additional:`

I can send over a few examples if needed.

Additionally, it'd be _really_ nice if the full path to that mtl was written in an <asset> tag  for further processing later :)

**Comment by vmxeo** [comment]
Doh. Look like it does this because I left off the trailing '/' on the -objdir parameter. Probably should have checked this better before I filed an issue

**Comment by Markemp** [comment]
Going to reopen this to fix the trailing / issue.  It shouldn't be required.

There are issues with the mtl file processing due to limitations on the data stored in the cgf files though.  The program makes a best effort attempt to find the mtl file, but since it can be anywhere in the Data directory (not in a child dir for example), there's always a good chance it can't be found.

**Comment by coloradocomputerpro** [comment]
to collect and write the mtl file name I used the following, this now writes a custom tag in the .dae with a reference name at a minimum. powershell get-childitem can uncover a robust search after the fact

in COLLADA.cs after line 111
insert
```
            asset.Extra = new Grendgine_Collada_Extra[]
            {
                new Grendgine_Collada_Extra()
                {
                    Type = "mtl_file",
                    ID = this.CryData.MtlFile
                }
            };
```

and in CryEngine.cs before line 91
insert
```
                if (materialFile.Extension == ".mtl")
                {
                    this.MtlFile = materialFile.Name;
                    //Console.WriteLine(materialFile.Name);

                }
```

**Comment by Kjasi** [comment]
> to collect and write the mtl file name I used the following, this now writes a custom tag in the .dae with a reference name at a minimum. powershell get-childitem can uncover a robust search after the fact

I love this idea, as it is often difficult to find the correct material file used by the model.

An alternative would be to write a new xml material file containing the referenced materials items. So if it uses glass_ext from cutlass_red.mtl but greymetal02b from cutlass_black.mtl, both of those material node trees would end up together in the exportedCutlassMaterials.xml, alongside the dae file. This would aid greatly in reconstruction, as I don't have to scour the Data folder for the correct mlt files, and guess which entry is correct.

**Comment by vmxeo** [comment]
> An alternative would be to write a new xml material file containing the referenced materials items. So if it uses glass_ext from cutlass_red.mtl but greymetal02b from cutlass_black.mtl, both of those material node trees would end up together in the exportedCutlassMaterials.xml, alongside the dae file. This would aid greatly in reconstruction, as I don't have to scour the Data folder for the correct mlt files, and guess which entry is correct.

Just a quick fyi, that would be something SC specific, and might be better off in a separate SOC conversion tool, which usually contains the references to additional mtl files.

**Comment by Markemp** [comment]
One thing I've experimented with is making a complete materials library from all the .mtl files in a game folder.  This would allow you to find the material by name, with all the textures that are associated with it.

One of the issues with this though is duplicate material names.  I wish the game files had a unique identifier for all the materials and referenced that instead of the material name, but... yeah.  At least it would give you the option to select which of the materials with a given name you would like to use.

**Comment by coloradocomputerpro** [comment]
Here is an example of my method, this allows for the most agnostic post-processing of texture data outside of the conversion. I continue to recommend this RFE.

![image](https://user-images.githubusercontent.com/48161657/120505615-5e49ed00-c382-11eb-82b0-a2e2903465f6.png)

**Comment by Kjasi** [comment]
> One thing I've experimented with is making a complete materials library from all the .mtl files in a game folder. This would allow you to find the material by name, with all the textures that are associated with it.
> 
> One of the issues with this though is duplicate material names. I wish the game files had a unique identifier for all the materials and referenced that instead of the material name, but... yeah. At least it would give you the option to select which of the materials with a given name you would like to use.

I'm not sure that's completely necessary. I know that (at least with Star Citizen) they list multiple mtl files in the models. In digging into it, I think it's a composited material listing. Materials with the same names in materials from lower on the list overwrite the older materials. For example, glass_ext from CutlassBlack.mtl would be overridden by glass_ext from CutlassRed.mtl if CutlassRed.mtl was listed after CutlassBlack.mtl on the material list.

**Comment by vmxeo** [comment]
Ok, I think I found part of the problem in Cryengine.cs:

`                // The Replace part is for SC files that point to a _core material file that doesn't exist.
                string cleanName = mtlChunk.Name.Replace("_core", "");
`

There are newer assets that properly use  '_core' in the material name now. Finally figured out why the materials weren't getting picked up during conversion.

**Comment by Markemp** [comment]
@Kjasi "I know that (at least with Star Citizen) they list multiple mtl files in the models."

Can you confirm this?  From my understanding each file has a single material file, with multiple materials defined within.  I haven't seen a file with more than 1 .mtl file.

**Comment by Kjasi** [comment]
@Markemp "Can you confirm this? From my understanding each file has a single material file, with multiple materials defined within. I haven't seen a file with more than 1 .mtl file."

Yes I can. 3.13.1\Data\Objects\Spaceships\Ships\DRAK\Cutlass\DRAK_Cutlass_Red.cga and cgam have two, and there is likely others with 2 or more: 
`Processing DRAK_Cutlass_Red.cga...
  MaterialName: Chunk Type: MtlName, ID: A9C, Material Name: Objects/Spaceships/Ships/DRAK/Cutlass/Cutlass_Red/DRAK_Cutlass_Red, Number of Children: 61, Material Type: Library
  MaterialName: Chunk Type: MtlName, ID: A9D, Material Name: Objects/Spaceships/Ships/DRAK/Cutlass/Cutlass_Black/DRAK_Cutlass_Black, Number of Children: 57, Material Type: Library
Processing DRAK_Cutlass_Red.cgam...
  MaterialName: Chunk Type: MtlName, ID: 1, Material Name: Objects/Spaceships/Ships/DRAK/Cutlass/Cutlass_Red/DRAK_Cutlass_Red, Number of Children: 61, Material Type: Library
  MaterialName: Chunk Type: MtlName, ID: 2, Material Name: Objects/Spaceships/Ships/DRAK/Cutlass/Cutlass_Black/DRAK_Cutlass_Black, Number of Children: 57, Material Type: Library`

That was outputted with your program. (I added some print strings...)

**Comment by Markemp** [comment]
Added MtlFile property and Collada extension from @coloradocomputerpro.  Just a couple of changes.  `id` is set to `material_file_name` as it's a way within the Collada document to reference that object.  `name` is set to the material file name, and type is still `mtl_file`.

I also got rid of the `_core` as it was a hard-coded hack.  Not sure how that will impact the cases where it had to be implemented, but if it's an issue I can look at coming up with a more elegant solution.

Releasing v1.2.0 here in a minute (minor version update due to framework upgrade).

**Comment by Markemp** [comment]
... Are all SC files now in .socpak files?  Ugh... I'm a bit out of the loop on this.  Is there an extractor for them?  Is it just another packed file in the .pak file?

**Comment by vmxeo** [comment]
from what we've figured out - SOCpak are 7z archives, and contain a mix of soc files and xml. The soc files are a join of a yet to be completely crack format and more xml.

**Comment by Kjasi** [comment]
@vmxeo is right. .socpak is basically a .pak file containing .soc. (Easily unzipped.) A quick glance at the file in notepad++ shows that the .soc files identify themselves as CrCh, and have links to meshes, (such as objects/spaceships/ships/drak/buccaneer/interior/drak_buccaneer_cockpit.cgf) and a palette tint reference (Libs/Foundry/Records/TintPalettes/default) but also a lot of entities and position, rotation, and other items. This format will (if I understand CIG correctly) replace the setup XML files in the very near future.

**Comment by vmxeo** [comment]
Just a suggestion - instead of leaving _instance_materials_ blank, perhaps a dummy material(s) could be inserted in? Again I think this is really a fault with the Blender's poor handling of Collada schema validation (treating warning as fatal errors), but this might work around it for now.

Oh, and if you're up for the back story on Blender's Collada importer: https://code.blender.org/2016/10/the-collada-case/

**Comment by ventorvar** [comment]
I'll agree that `.socpak`/`.soc` files probably don't belong in cgf-converter. They're SC only and essentially replace prefabs which cgf-converter doesn't touch anyway.

If you're interested though `scdatatools`/SCDV do process these -> https://gitlab.com/scmodding/tools/scdv. Specifically, https://gitlab.com/scmodding/frameworks/scdatatools/-/blob/devel/scdatatools/cry/model/chunks/defs.py#L47. Dymek's exporting toolkit had started down that path, but the format has changed since that tool was last updated.
