### ISSUE TITLE
Hunt Showdown support

### ISSUE THREAD

**Issue by dkl77** [Markemp/Cryengine-Converter#55]
Hello, in the cryengine 5 version of the hunt showdown, the tool works quite well, only in some specific models it seems that the chunks of the vertices have changed because the mesh of the models is imported deformed in a specific way. In the xentax forum I left you a link to some of them, if at any time you can take a look at it, it would be great 
[Hunt_models_problems.zip](https://github.com/Markemp/Cryengine-Converter/files/6620924/Hunt_models_problems.zip)
[https://forum.xentax.com/viewtopic.php?f=33&t=13137&p=175234#p175234](url)

**Comment by Markemp** [comment]
Got a fix pushed up to master.  Will generate a release this weekend once I can verify it doesn't break Star Citizen files.

**Comment by Markemp** [comment]
Release v1.1.1 added to support the new Hunt models.  Let me know if you run into additional issues.

https://github.com/Markemp/Cryengine-Converter/releases/latest
