### ISSUE TITLE
Latest release generating invalid data in DAE

### ISSUE THREAD

**Issue by vmxeo** [Markemp/Cryengine-Converter#58]
File conversion on the latest release is generating non-valid vertex data when running on Star Citizen files from multiple versions. Examples of parsing errors are as follows:

```
Schema validation (Warning): Error: ERROR_TEXTDATA_PARSING_FAILED Element: float_array, Line: 1922, Column: 148375, Additional:  -E♥
Schema validation (Warning): Error: ERROR_TEXTDATA_PARSING_FAILED Element: float_array, Line: 1922, Column: 148973, Additional: Γê₧ -185.438908 0.00
Schema validation (Warning): Error: ERROR_TEXTDATA_PARSING_FAILED Element: float_array, Line: 1922, Column: 150469, Additional: Γê₧ -185.438908 0.00
Schema validation (Warning): Error: ERROR_TEXTDATA_PARSING_FAILED Element: float_array, Line: 1922, Column: 150765, Additional: Γê₧ -185.438908 -412
Schema validation (Warning): Error: ERROR_TEXTDATA_PARSING_FAILED Element: float_array, Line: 1922, Column: 160365, Additional: Na
```

This will crash most software, and I believe may not be intended :)

**Comment by Markemp** [comment]
Bah!  

When you look at the .dae file, are you seeing NaN entries like this?

![image](https://user-images.githubusercontent.com/12057128/121814077-03d34b00-cc24-11eb-98cf-772545356360.png)

**Comment by vmxeo** [comment]
Many, many NaNs :)

**Comment by Markemp** [comment]
This may be a problem.  Both Hunt and Star Citizen use 16 byte structures for the VertsUVs, and it looks like they use different methods to get the values out.  I'll have to see what options I have. :(

**Comment by Baconator650** [comment]
Sounds variations will be needed one for Hunt and another for Star Citizen; or add an instruction to jump between the two different methods.

**Comment by Markemp** [comment]
Ish, gross! :)  .Net 5.0 has a native Half float structure, which maybe will work across different models.  There is a pretty high likelihood that my Half implementation is fully baked. 

I'm going to put another pin in the voodoo doll that is "CIG creating custom models". 😡

**Comment by Baconator650** [comment]
May want to put a pin in other  voodoo dolls in that set, that also includes "CIG creating custom materials" and "CIG creating custom prefabs called object containers"

**Comment by Markemp** [comment]
Oof.  Too soon.  Save these emotional beat-downs for when the game is released! ;)

**Comment by Baconator650** [comment]
At least object container decoding has made some strides recently.

**Comment by Markemp** [comment]
Found a data structure in Star Citizen data streams for VertsUVs (right after bytes per element) that seems to indicate that SC is using a different format, even though the chunk versions are identical.  It seems to have fixed the conflict between SC and every other newer format.  Should have a fix out today. 

This includes updating the framework to .Net 5.0.  The integration tests now run about twice as fast, so I'm hoping that overall performance of the converter is likewise significantly improved.  I've never done any profiling/baselining to check though. :(

**Comment by Baconator650** [comment]
With 3.14 coming out soon, this will be coming out at a good time.

**Comment by Markemp** [comment]
v1.2.0 released to fix this issue.  If this doesn't work quite right, let me know and I'll reopen the issue.
