### ISSUE TITLE
[REQUEST] Star Citizen Prefab and Object Container File XML to .DAE

### ISSUE THREAD

**Issue by Baconator650** [Markemp/Cryengine-Converter#59]
Request to add an addition Cry Engine/Star Citizen File format to the CGF-Converter, as to serve as method for non-Blender users to import Prefab/Object Container data. 

- Converter will read a variety of prefab data (Standard Cry Engine XML and Converter SOC (located in .socpak) and converter them into a .dae file.

- Objects Entities (cga, cfg, skin) create a dummy/helper with position/rotation/scale and maintain appropriate hierarchy.

- Light Entities create a standard light with the appropriate data from the .xml OR creates a dummy/helper like object entities

- Additional/Unknown entities:  dummy/helper with position/rotation/scale and maintain appropriate hierarchy.

- Entities with missing positional data: do not create any dummy/helper or with default pos/rot/scale.  

Current Star Citizen .socpak to xml conversion as found here: https://www.youtube.com/watch?v=1wQWaif5DUc&list=PLr5XU4B6R4l7fvfdTehSfAZb2QDd0HFjH&index=9

**Comment by Markemp** [comment]
This doesn't look too bad.  Check out the prefab stuff for Cryengine Importer.  It's python and can read olde timey prefab objects, including the binary CryXmlB format.  The format looks very similar to what is in the socpak XML files here.  The Import Prefab function will go through a prefab file and import all the known objects (including lights, particle emitters, etc) into a Blender scene.

It may make more sense to create a specific importer for your particular modeling software though.  socpak files are a lot different than the geometry files.  Which 3D modeling software do you use?  I'm assuming it has some built in ability to make add-ons to help with the importing.

Having a custom importer will also allow you to import the whole prefab in a single go.  Cryengine Importer will look for the .dae files for the geometry/entities referenced in the XML and import those as well.  Anyway... lots of options.  

What is your ideal workflow for your specific use case?

**Comment by Baconator650** [comment]
I am a 3DS max user, so it would use some sort of maxscript or plugin. I am wrestling with the Blender Cryengine Importer, but its still giving me some errors with the importation (seat_access gives it a lot of problems). 

Two reasons for this type of request is: 
-Agnostic to different 3D Software
-Less complicated=less likely to have issues with missing/problematic files 

My general workflow is found here: https://www.youtube.com/playlist?list=PLr5XU4B6R4l7fvfdTehSfAZb2QDd0HFjH

For ships with complex/walkable interiors, I have been mostly working on ones with olde timey prefabs and load them in the Modded CryEngine from Bulkheads, destroy the hierarchy and export them via the .fbx (text) exporter. Load them into Max, which loads all the cgf files as dummy/helpers (w/ pos/rot/scale) and 90% of the .cga files as such. The ship exterior and doors usually load correctly in as single objects. 

Request would mimic my current workflow for walkable ships, but would be able to use the newer object containers. 

Took forever to the Hammerhead
![image](https://user-images.githubusercontent.com/78010776/125179321-4bada980-e1b3-11eb-8b04-6f4ae59baa97.png)

**Comment by peter-dolkens** [comment]
Hi @Baconator650 - one thing I did notice in your video is you're using very old versions of some of those tools.

I had to update unp4k/unforge just last build for example - so always a good idea to grab the latest builds as SC tweaks their formats constantly.

**Comment by Baconator650** [comment]
Right now, it looks like there is some more work to be done on decoding the .soc files in the socpak. The current method completely deletes the coordinates for geo entities that use .cgf files. 

To be said, an update to the Blender plugin to read these new file formats (users may still be required to extract and convert the ,soc) would work for me, as I can load it into Blender and export it as a .fbx so Max to import it. I'd would request for the Blender to have an option to import geometry as a helper/dummy to help, this would be useful for my workflow and also would make it easier for Blender users to import and not have total import failure due to missing files.

**Comment by vmxeo** [comment]
@Baconator650 I cleaned up my own Blender prefab script and uploaded it here: https://github.com/vmxeo/SCTools
What I don't have yet is documentation. Soonish hopefully.

**Comment by Baconator650** [comment]
> @Baconator650 I cleaned up my own Blender prefab script and uploaded it here: https://github.com/vmxeo/SCTools
> What I don't have yet is documentation. Soonish hopefully.

Thank you for this. Been playing around with it like an orangutan with a hammer, think I mostly figured out how it works. I do like the workflow is that you pull the need objects via the .dae/.obj then import into the scene, instead of having a separate .blend file to source from. Might be an idea for the new Blender plugin to adopt or have an option for, as there are some pros to having the .blend file as the source for Blender users. As someone who is just using Blender as a intermediate to Max, your workflow is more advantageous to me.

**Comment by ventorvar** [comment]
After getting _way_ too deep into this, it may be too game-specific for what cgf-converter's goals are, that begs the question though, how game-specific does cgf-converter want to get? At this point, SCDV will generate the information required to reassemble an entire asset from SC, but it's hundreds if not thousands of lines of code (and python, so you know, pseudo-code) to be able to parse the required formats, structures, and generate the relationships.

**Comment by Baconator650** [comment]
Think SCDV definitely obsoleted the need for this feature.
