### ISSUE TITLE
float_type uses coma instead of period

### ISSUE THREAD

**Issue by Levak** [Markemp/Cryengine-Converter#6]
**Issue**: All floating point numbers that appear in the final DAE file use coma (`,`) as decimal separator instead of a period (`.`).

Hi,

First and foremost, thank you for this tool. It has its temper at first, but when you get the hang of it, it does the job. My main criticism so far is that every time I need to export to DAE, I need to replace with a text editor all comas with periods before importing it into Blender (v2.78).

I looked at the COLLADA standard[1] Ch.11 p. 501, and it seems Blender is correct to refuse floats with comas. as `float_type` seems to inherit from ` xs:double` which is by the XML standard [2] "4.4.1. Decimal types" supposed to only accept period as decimal separator.

For now, I can live without a fix, using Search&Replace, not a big deal.
Best regards,

[1]: https://www.khronos.org/files/collada_spec_1_5.pdf
[2]: https://docstore.mik.ua/orelly/xml/schema/ch04_04.htm

**Comment by Levak** [comment]
I just realized that this might be caused by C# localization of doubles
I use French localization on my system.

Looking at the source code[1] makes me remember having such issue when doing my own C# projects. AFAIR, there is a C# way to force the decimal separator to be a period, no matter localization parameters.

[1]: https://github.com/Markemp/Cryengine-Converter/blob/github-master/cgf-converter/Renderers/Collada/COLLADA.cs#L1282

**Comment by Levak** [comment]
Update: I added the lines mentioned above in cgf-converter.cs ' Main[1] function and it solved the issue on my side:

```cs
System.Globalization.CultureInfo customCulture = (System.Globalization.CultureInfo)System.Threading.Thread.CurrentThread.CurrentCulture.Clone();
customCulture.NumberFormat.NumberDecimalSeparator = ".";

System.Threading.Thread.CurrentThread.CurrentCulture = customCulture;
```

[1]: https://github.com/Markemp/Cryengine-Converter/blob/github-master/cgf-converter/cgf-converter.cs#L20

**Comment by Markemp** [comment]
Thank you!  I'll get this added to the next release as well.

**Comment by Markemp** [comment]
Added your code to the start of the program.  I don't have any way of testing this, so if this still isn't working right, please let me know.  Thank you!
