### ISSUE TITLE
Blender Import Error

### ISSUE THREAD

**Issue by Baconator650** [Markemp/Cryengine-Converter#60]
![image](https://user-images.githubusercontent.com/78010776/125474519-f4aa8094-e83e-4f1a-9a37-8da53e7b742f.png)

Working on using CryEngine Importer and trying to nail down the errors and notice that when Importing (using the standard Collada Importer, not he CryEngine Importer).

Workaround: Used Noesis to convert the dae to dae. Blender will load the *_out.dae.

Not an issue with Max.

**Comment by vmxeo** [comment]
Yeah that's the error from issue #54 - if the material file isn't found, instance_material doesn't get written to. Blender DAE importer really should treat this as a warning and not a fatal error, but that's a whole other can of worms.

**Comment by Baconator650** [comment]
The funny part on trying to get around some of the errors was to run CGF-Converter with no MTL in it. Fixes most of the issues, but there are few files that need to be converted over with Noesis. Plan is to use the Blender to load the old prefabs and the objects would be Proxies, and then import the scene into max and replace the proxies with the proper object that has materials and is cleaned up.

**Comment by vmxeo** [comment]
So I actually have a Blender python importer for prefabs - it's a mess of code and really needs to be cleaned up but I've used it to build out a number of older and newer prefabs. Here's the old Arc Corp LZ: https://i.redd.it/7wjbflq33nt61.png

**Comment by Markemp** [comment]
@vmxeo is that from my Cryengine Importer blender addon?  I've been also making some major updates to the Import Prefab feature there, and soon it should be able to handle a lot more stuff.  I plan on eventually getting it to handle soc/sokpak files as well.

**Comment by vmxeo** [comment]
No, I wrote my own from scratch. It works, but it's not pretty. It's also got some optimizations to work with the larger prefabs.

**Comment by Baconator650** [comment]
> @vmxeo is that from my Cryengine Importer blender addon? I've been also making some major updates to the Import Prefab feature there, and soon it should be able to handle a lot more stuff. I plan on eventually getting it to handle soc/sokpak files as well.

And batch directory importing?

**Comment by Markemp** [comment]
This issue may be resolved with the merge of https://github.com/Markemp/Cryengine-Converter/pull/69.

**Comment by Markemp** [comment]
v1.3.1 should fix this.  Just uploaded an updated release candidate this morning, so give it a try.  Thanks!

**Comment by Markemp** [comment]
Closing as this should be resolved.
