### ISSUE TITLE
CGF may not contain Specular data

### ISSUE THREAD

**Issue by Levak** [Markemp/Cryengine-Converter#7]
**Issue**: cgf-converter crashes when a CGF has no specular data.

```
cgf-converter.exe -objectdir xxxxx xxxxx\Objects\Weapons\Shells\shell_scargrenade\scar_gl_grenade.cgf
Data directory set to xxxxx
Input file set to xxxxx\Objects\Weapons\Shells\shell_scargrenade\scar_gl_grenade.cgf

********************************************************************************
There was an error rendering xxxxx\Objects\Weapons\Shells\shell_scargrenade\scar_gl_grenade.cgf

Null reference exception

   in CgfConverter.COLLADA.WriteLibrary_Effects()
   in CgfConverter.COLLADA.Render(String outputDir, Boolean preservePath)
   in CgfConverter.Program.Main(String[] args)
********************************************************************************
```

Using Visual Studio to debug yields to this line:
![capture](https://user-images.githubusercontent.com/2292040/32511258-8244c4d8-c3f3-11e7-9685-f93d9808a7b8.JPG)

Where `__Specular` seems to be null. I suppose the object has no specular attribute. Might be worth adding several guards before referencing to parsed data.

Adding conditions to prevent the null pointer ref prevents the crash:
![capture](https://user-images.githubusercontent.com/2292040/32511797-2b980b0c-c3f5-11e7-8900-913ee11b56b7.JPG)

**Comment by Markemp** [comment]
Added this fix.   The program needs a good thorough washing of null reference issues.  Added a Tests project to help prevent this in the future.
