### ISSUE TITLE
Hunt Showdown converted model files not showing anything in Blender

### ISSUE THREAD

**Issue by sethlangel** [Markemp/Cryengine-Converter#70]
So I found a way to decrypt the .pak files and find the model files, converted them successfully but when I put the .dae files into blender they go into blender with no errors but there is no model that shows with the file. Any help?

**Comment by sethlangel** [comment]
I am trying to pull the Butcher's model with his weapon and when I import the .dae into blender nothing shows, I then tried to pull other files to see if it was the butcher that was giving me trouble and I could not get any of the .dae files to show in blender

**Comment by sethlangel** [comment]
Is anyone else having this issue or am I the only one experiencing this?

**Comment by Markemp** [comment]
Are you able to convert the assassin .skin models?  I don't have the game, so can't test the Butcher models.

Not exactly sure where the file is found, but it's called `assassin_body.skin` (and the related skinm file).

**Comment by sethlangel** [comment]
I tried it when I couldnt get the butcher to appear in blender and when I did the assassin something did pop up in blender but it was just shapes and not really a character model

**Comment by Markemp** [comment]
Can you download the v1.3.1 candidate from https://github.com/Markemp/Cryengine-Converter/releases and try that on those models?

**Comment by Murkur** [comment]
ive been unable to actaully find a way to extract the paks seems they are RSA encrpyted

**Comment by sethlangel** [comment]
I tried converting the file "assassin_body.skin" and got it into a .dae file but when imported into blender again nothing pops up.

**Comment by Murkur** [comment]
are you sure what your exporting is actual data? what's the size of the extracted .dae?

**Comment by Markemp** [comment]
@sethlangel , can you upload the .dae file to this issue?  I'll take a look and see if I can figure out what is going on.

There is also a draft 1.3.1 release that may fix this.  I've added it to the zip file below.  Give that one a try as well, and if it doesn't work please upload that .dae file too.

[cgf-converter.zip](https://github.com/Markemp/Cryengine-Converter/files/6886870/cgf-converter.zip)

**Comment by Murkur** [comment]
I can upload the games character.pak file aswell if that will help with extraction though I do not know how to extract the encrypted pak files myself.

**Comment by Murkur** [comment]
the characters.PAK is all under 50MB 
[Characters.Pak HuntShowdown Latest Patch](https://cdn.discordapp.com/attachments/493153303551541258/869276230132834324/characters.pak)

**Comment by Markemp** [comment]
Can you check this with the v1.3.1 release?  I'm able to convert all the Hunt models I have so far, so assuming this problem is solved.

**Comment by Murkur** [comment]
> Can you check this with the v1.3.1 release? I'm able to convert all the Hunt models I have so far, so assuming this problem is solved.

I dont know how to extract the pak files so I cant say, i could provide more sample files

**Comment by Markemp** [comment]
I am unable to extract that file from above either.  Since this issue appears to be resolved, I'm going to close it.  If you are able to find a way to extract the files and can find specific ones that don't work, please open a new issue.  Thank you!

**Comment by Murkur** [comment]
> I am unable to extract that file from above either. Since this issue appears to be resolved, I'm going to close it. If you are able to find a way to extract the files and can find specific ones that don't work, please open a new issue. Thank you!

@sethlangel would have to provide the way till then
