### ISSUE TITLE
Conversion freezes with 1.3.0 while processing Skin Files

### ISSUE THREAD

**Issue by Kjasi** [Markemp/Cryengine-Converter#72]
Conversion freezes with 1.3.0 while processing `Data\Objects\Characters\Human\male_v7\armor\ccc\m_ccc_vanduul_helmet_01.skin`

options: `-noconflict -tif -dae -smooth -objectdir 'R:\StarCitizen\Extracted\3.13.1\Data'`
Output:
>Processing R:\StarCitizen\Extracted\3.13.1\Data\Objects\Characters\Human\male_v7\armor\ccc\m_ccc_vanduul_helmet_01.skin...
Input file set to R:\StarCitizen\Extracted\3.13.1\Data\Objects\Characters\Human\male_v7\armor\ccc\m_ccc_vanduul_helmet_01.skin
Prevent conflicts for mtl files enabled
Output format set to COLLADA (.dae)
Smoothing Faces
Data directory set to R:\StarCitizen\Extracted\3.13.1\Data

But no file is exported. Other files in the same directory, such as `Objects\Characters\Human\male_v7\armor\ccc\m_ccc_bear_helmet_01.skin`, `m_ccc_medium_armor_arms_01.skin`, `m_ccc_medium_armor_core_01.skin`, and `m_ccc_medium_armor_legs_01.skin`, convert to DAE just fine, but have an incorrect armature imported. (Issue #73)

**Comment by ventorvar** [comment]
Took a brief look into this. the `ChunkIvoSkin_900` is getting stuck in an infinite loop in [Read](https://github.com/Markemp/Cryengine-Converter/blob/ce01ab27f5905a6bf44583125b44683766588337/CgfConverter/CryEngineCore/Chunks/ChunkDatastream_900.cs#L24) do to an unknown `DataStreamType` `0x38A581FE`.

In `Objects/Spaceships/Ships/AEGS/LandingGear/Vanguard/AEGS_Vanguard_LandingGear_Front.skinm` (SC build 7666961) this occurs as offset `346944` where it appears to be followed by a `uint32` (4 in this case), and then a _long_ stream of data that doesn't immediately look obvious to me.

I've uploaded in the offending files in the shared folder you've got access to @Markemp

**Comment by Markemp** [comment]
I think that's a new Normals chunk.  The uint of 4 is the number of bytes per element.  In the Behr rifle parts (3.12, `brfl_fps_behr_p4ar_parts`), there is a Normals chunk that uses the datastream type of 0x9CF3F615.  I don't know if 3.13/14 have the same datastream type id, but might be worth checking out.  

It is in the same relative position of the datastream chunks as the rifle normals  (VertsUVs, then Normals, then Tangents).  So... I'm guessing Normals and will treat it like that pending more info.

**Comment by Markemp** [comment]
`AEGS_Vanguard_LandingGear_Front.skin` should work now, aside from the armature.  See the draft v1.3.1 release.

Still have to sort out the morph shapes structure though, so leaving this issue open for now.

**Comment by Kjasi** [comment]
1.3.1 Preview still hangs.
```
Converting Models...
Processing R:\StarCitizen\Extracted\3.13.1\Data\Objects\Characters\Human\male_v7\armor\ccc\m_ccc_bear_helmet_01.cgf...
Processing R:\StarCitizen\Extracted\3.13.1\Data\Objects\Characters\Human\male_v7\armor\ccc\m_ccc_heavy_armor_helmet_01.cgf...
Processing R:\StarCitizen\Extracted\3.13.1\Data\Objects\Characters\Human\male_v7\armor\ccc\m_ccc_scarecrow_helmet_01.cgf...
Processing R:\StarCitizen\Extracted\3.13.1\Data\Objects\Characters\Human\male_v7\armor\ccc\m_ccc_vanduul_helmet_01.cgf...
Processing R:\StarCitizen\Extracted\3.13.1\Data\Objects\Characters\Human\male_v7\armor\ccc\m_ccc_vanduul_helmet_01_prop.cgf...
Processing R:\StarCitizen\Extracted\3.13.1\Data\Objects\Characters\Human\male_v7\armor\ccc\m_ccc_bear_helmet_01.skin...
Skipped node with missing Object m_ccc_bear_helmet_01.skin
Processing R:\StarCitizen\Extracted\3.13.1\Data\Objects\Characters\Human\male_v7\armor\ccc\m_ccc_bear_helmet_01_int.skin...
```
