### ISSUE TITLE
CGF may contain PhysicsData *AND* Mesh

### ISSUE THREAD

**Issue by Levak** [Markemp/Cryengine-Converter#8]
**Issue**: If a CGF contains a node that has a `PhysicsData` attribute, the mesh geometry node is discarded while it could be imported

Replacing the `else if` to a simple `if` in `COLLADA.cs:489`[1] solves the lack of mesh geometry in the scene (which led to an error on import).

![capture](https://user-images.githubusercontent.com/2292040/32513754-5d466792-c3fb-11e7-8d59-a3d67556e9f9.JPG)

[1]: https://github.com/Markemp/Cryengine-Converter/blob/github-master/cgf-converter/Renderers/Collada/COLLADA.cs#L489

**Comment by Markemp** [comment]
I'll get this change added this upcoming weekend, in a 1.0.2 release.  Thank you for the report, as well as the other reports you made!  I really appreciate it.

**Comment by Markemp** [comment]
Removed the else in the line you identified.  The implementation of MeshPhysicsData still needs to happen.
